GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/6549275cf714d808c1f59192

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample",
    "number": "123-456-7890"
}